version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/usr/client
